### ISSUE TITLE
Bad Parsing of technique Mitre

### ISSUE THREAD

**Issue by vinceplayer** [ioc-fang/ioc-fanger#81]
How can I avoid the fang of mitre techniques, e.g., " Credential Access [TA0006]," becomes "Credential Access [TA0006.
?
Thank you

**Comment by fhightower** [comment]
Thanks for reporting this, @vinceplayer! I'll take a look in the next few days.

**Comment by fhightower** [comment]
This is being replaced by the fanging pattern [here](https://github.com/ioc-fang/ioc-fanger/blob/2316a003a5a789c333cac937d3b7f120e25c27df/ioc_fanger/fang.json#L3). This fanging pattern will be removed/modified by #49 so that `Credential Access [TA0006],` would remain unmodified.

I don't have the bandwidth to work on #49 now, but hope to work on it over the next couple of weeks.

**Comment by fhightower** [comment]
Sorry about the delay on resolving this @vinceplayer, but this is resolved in the newest version (`4.1.0`). Thanks again for raising this issue!
